---
- name: Load starship vars
  ansible.builtin.include_vars:
    file: vars/starship_vars.yml

- name: Install Github CLI
  ansible.builtin.import_tasks: tasks/github.yml
  when: install.github
  tags:
    - github

- name: Install VSCode
  ansible.builtin.import_tasks: tasks/vscode.yml
  when: install.vscode
  tags:
    - vscode

- name: Install Insomnia
  ansible.builtin.import_tasks: tasks/insomnia.yml
  when: install.insomnia
  tags:
    - insomnia

- name: Install Docker
  ansible.builtin.import_tasks: tasks/docker.yml
  when: install.docker
  tags:
    - docker

- name: Install Obsidian
  ansible.builtin.import_tasks: tasks/obsidian.yml
  when: install.obsidian
  tags:
    - obsidian

- name: Install Neovim
  ansible.builtin.import_tasks: tasks/neovim.yml
  when: install.neovim
  tags:
    - neovim

- name: Install lazydocker (Requires Go)
  ansible.builtin.import_tasks: tasks/lazydocker.yml
  when: install.lazydocker
  tags:
    - lazydocker

- name: Install Starship
  ansible.builtin.import_tasks: tasks/starship.yml
  when: install.starship
  tags:
    - starship

- name: Install intellij
  ansible.builtin.import_tasks: tasks/intellij.yml
  when: install.intellij
  tags:
    - intellij

- name: Install DevPod
  ansible.builtin.import_tasks: tasks/devpod.yml
  when: install.devpod 
  tags:
    - devpod
